#1
sudo: required
#2
services:
  - docker
#3
before_install:
  - docker build -t bear2u/docker-react -f Dockerfile.dev .
#4
script:
  - docker run bear2u/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "dokcer-react"
  env: "DDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-110932418490"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
